run-name: Build ${{ inputs.base_name }} badges

on:
  workflow_call:
    inputs:
      base_name:
        required: true
        type: string

jobs:
  badges:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./build_results

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v3
      - name: Setup NodeJs 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: build_results/package-lock.json
      #- name: Cache dependencies and build outputs to improve workflow execution time.
      #  uses: actions/cache@v3
      #  with:
      #    path: node_modules
      #    key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate badges file
        run: node ${{ inputs.base_name }}.js
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated badges generation
          file_pattern: 'build_results/*.md build_results/badges/*.svg'
